[package]
name    = "rust_prime"
version = "0.1.0"
authors = ["Damian J Pound <damian@thebestisp.com>"]
edition = "2024"

[profile.release]
debug = true

[dependencies]
chili        = "0.2.1"
orx-parallel = "3.4.0"
rayon        = "1.11.0"
